### ISSUE TITLE
Cannot find tyk in marketplace

### ISSUE THREAD

**Issue by franz-see** [TykTechnologies/vscode-tyk#14]
I am in Manjaro Linux if that helps/matters

**Comment by buraksekili** [comment]
hi @franz-see, thanks for raising this issue. this looks interesting since the extension is served through a platform-independent marketplace. can you please check if you can install the extension through this link https://marketplace.visualstudio.com/items?itemName=TykTechnologiesLimited.tyk-schemas?

**Comment by buraksekili** [comment]
hi @franz-see, do you still face this issue? If you have resolved it, we can close this issue.
